name:                hpffp
version:             0.1.0.0
github:              "thadeudepaula/haskell-exercises"
license:             BSD3
author:              "Thadeu de Paula"
maintainer:          "thadeudepaula@gmail.com"
copyright:           "2022 Author name here"

extra-source-files:
- data/dict.txt

description:         See README.md

dependencies:
- base >= 4.7 && < 5
- time
- random
- split

library:
  source-dirs: src

executables:
  hpffp-hangman:
    main:                Main.hs
    source-dirs:         app/Hangman
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpffp

  hpffp-chipher:
    main:                Main.hs
    source-dirs:         app/Cipher
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpffp

tests:
  hpffp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hpffp
